### PR TITLE
Feature: mySQL Connector ODBC & NET

### PR DESCRIPTION
**Pull request by BornToBeRoot**
Hi @aaronparker,

2 new apps:
- mySQLConnectorNET

image

- mySQLConnectorODBC

image

image

Does the `Get-GitHubRepoRelease` always return the latest tag based on the version number or date published? If it's based on date published, there could be an issue with version 8.0.x (i think it's lts) because they changed the URL... since 8.1, 8.2 it should be the current format.

### CODE REVIEW

**Comment by aaronparker** [comment]
`Get-GitHubRepoRelease` will return the latest release based on what's tagged as the latest release on the repo.

**Comment by aaronparker** [comment]
There's also `Get-GitHubRepoTag` now to return the tags from the repo, from which you can then sort or filter via some other means.

**Comment by aaronparker** [comment]
You'll need to resolve the URLs from `dev.mysql.com`, e.g.:

```powershell
Resolve-InvokeWebRequest -Uri "https://dev.mysql.com/get/Downloads/Connector-ODBC/9.1/mysql-connector-odbc-9.1.0-winx64.msi"

https://cdn.mysql.com//Downloads/Connector-ODBC/9.1/mysql-connector-odbc-9.1.0-winx64.msi
```

**Comment by BornToBeRoot** [comment]
@aaronparker done 😄 

1) It works great with the repo tags.
2) It also resolves the redirect url to the cdn now.
3) I also updated the workbench to the new url and fixed an issue when the tag is like `major.minor.patch.build`, because the url only has `major.minor.patch` 

image

**Pull request merged**
